version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2

    steps:
      - checkout

      - run:
          name: install dependencies
          command: composer install

      - run:
          name: run tests
          command: ./vendor/bin/phpunit

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
